name: Deploy ASP.NET Core to MonsterASP

on:
  push:
    branches: ["master"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "10.0.104"

      - name: Publish with dotnet
        run: dotnet publish --configuration Release --output ./publish

      - name: Deploy via SFTP to MonsterASP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: 'site71373'  # Usuario correcto
          server: 'site71373.siteasp.net'  # Hostname correcto
          port: 22  # Puerto SFTP/SCP
          password: 'B+p4f2@R%bX7'  # Tu contraseña
          local_path: './publish/*'
          remote_path: '/wwwroot/'  # Ruta en el servidor
          sftp_only: true
          delete_remote_files: false